//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT2_InternationalWidgetWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLine
    {
        public int ItemID { get; set; }
        public int InvoiceNo { get; set; }
        public Nullable<int> ItemQTY { get; set; }
        public Nullable<double> ItemTotal { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Item Item { get; set; }
    }
}
